spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://178.128.52.39:5432/digital_asset_db'
    username: '{cipher}92dcb704f8d45708ed68efa4702afdc92499fc735f30e7f8f236f993dfd09150'
    password: '{cipher}5c1ecdb65474e50779c731476d94380bb6513ed9af9583522c13bbc2193afd25'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
#         https
          # issuer-uri: https://keycloak.trade-wise.store/auth/realms/go-selling-api
          # jwk-set-uri: https://keycloak.trade-wise.store/auth/realms/go-selling-api/protocol/openid-connect/certs
#          local
#          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
#          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://8.222.225.41:8761/eureka
# keycloak:
#   realm: go-selling-api
#   resource: go-selling
#   auth-server-url: https://keycloak.trade-wise.store/auth
#   credentials:
#     username: 'tradewise'
#     password: 'tradewise321'
#     client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
#     secret: '{cipher}68cb6ac579e956cea85bc0dfedfb1bfa31fb186ac71e0913bdb8772ba29899585595c9b431f585262b85836a3c0e02637e2863c8db3fa0e4ac8011f7093263d4'
#     provider: secret
# openapi:
#   service:
#     title: category-service
#     version: 1.0.0
#     # url: http://localhost:8080
#     url: http://8.222.225.41:8080

# springdoc:
#   api-docs:
#     path: /category-service/v3/api-docs
#   swagger-ui:
#     oauth:
#       realm: 'go-selling-api'
#       client-id: '{cipher}68cb01c2cb6cc09d52d307bb77df71dd6ea99df0449c664e7031b6cbb6529055'
#       clientSecret: '{cipher}68cb6ac579e956cea85bc0dfedfb1bfa31fb186ac71e0913bdb8772ba29899585595c9b431f585262b85836a3c0e02637e2863c8db3fa0e4ac8011f7093263d4'
#     path: /category-service/swagger-ui.html