spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://178.128.52.39:5432/digital_asset_db'
    username: '{cipher}92dcb704f8d45708ed68efa4702afdc92499fc735f30e7f8f236f993dfd09150'
    password: '{cipher}5c1ecdb65474e50779c731476d94380bb6513ed9af9583522c13bbc2193afd25'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
openapi:
  service:
    title: doc-service
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /doc-service/v3/api-docs
  swagger-ui:
    path: /product-service/swagger-ui.html  